### ISSUE TITLE
ITunes lookup API country param

### ISSUE THREAD

**Issue by se09deluca** [GantMan/react-native-siren#13]
Hi,
the request done in getLatest function should contain optionally a country code to enable the lookup for app restricted to a specific region.

See https://stackoverflow.com/questions/8839328/itunes-api-lookup-by-bundle-id 

I'm available to create a pull request.
Let me know.

Thanks

**Comment by GantMan** [comment]
Yes!  please do a PR!   Happy to merge it.

Also, would you be interested in being a maintainer?   I could always use help from anyone actively using the module!

**Comment by se09deluca** [comment]
Hello @GantMan 
Here is the pull request #14 

Yes, i can help you with this repo.

**Comment by GantMan** [comment]
I've merged and I added you to the repo.   What's your NPM username?

**Comment by se09deluca** [comment]
Excellent!
My npm username is 'se09deluca'..

**Comment by GantMan** [comment]
added!  Please try to publish this new version to be sure.

**Comment by se09deluca** [comment]
Oh thanks, just release a new version!
