### ISSUE TITLE
App link

### ISSUE THREAD

**Issue by winseyli** [GantMan/react-native-siren#6]
Think the app link http://itunes.apple.com/app/id[Apple_ID] is gone and the new one should be https://apps.apple.com/app/id[Apple_ID] ? And the uri starting with "itmss" should no longer be a valid case too. Thank you
![photo_2019-10-08_16-46-15](https://user-images.githubusercontent.com/7858565/66365927-30fd3e00-e9eb-11e9-8b83-7921d847509b.jpg)

**Comment by GantMan** [comment]
ah!  Would you want to make a PR since you found this?

If not, I'll fix.

**Comment by winseyli** [comment]
Kindly have a check

**Comment by GantMan** [comment]
perfect!

**Comment by winseyli** [comment]
@GantMan how can we have this as new release on `npm`? Thanks!

**Comment by GantMan** [comment]
Yup!   BTW, @winseyli - are you interested in getting access to release?   This project could use a second maintainer.

**Comment by winseyli** [comment]
Yes that sounds interesting! Thank you!

**Comment by GantMan** [comment]
@winseyli - I added you as a contributor on GitHub - what's your NPM username?

**Comment by winseyli** [comment]
just registered... same as the one on github :)

**Comment by GantMan** [comment]
awesome!  You've been added.   Let me know if you need any help.  You should have all the access you need to bump the version number and publish 👍
