### ISSUE TITLE
Bundle ID is wrong

### ISSUE THREAD

**Issue by Rubenvdveen** [GantMan/react-native-siren#9]
I ran into an error while using `sp-react-native-in-app-updates`, which uses this package for iOS. The return status was "Could not fetch the latest version". 

After debugging I found out that the Bundle ID that `react-native-device-info` got, was wrong. Something with brackets and some key/values. 

I know this is more of a problem in `react-native-device-info`, but maybe this package should allow you to pass your own Bundle ID as an optional parameter? That would fix the issue for me.

**Comment by GantMan** [comment]
Sounds good.  PR welcome

**Comment by Rubenvdveen** [comment]
@GantMan done :). Thanks for the quick response.
